override flush method to write udev rules...
the only problem is that so far this udev provider is choking because:

    Error: Could not run: undefined method `find' for nil:NilClass
    /home/igalic/.gem/ruby/2.1.2/gems/puppet-3.6.2/lib/puppet/provider.rb:295:in `default_match'
    /home/igalic/.gem/ruby/2.1.2/gems/puppet-3.6.2/lib/puppet/provider.rb:287:in `default?'
    /home/igalic/.gem/ruby/2.1.2/gems/puppet-3.6.2/lib/puppet/type.rb:1654:in `block in defaultprovider'
    /home/igalic/.gem/ruby/2.1.2/gems/puppet-3.6.2/lib/puppet/type.rb:1654:in `each'
    /home/igalic/.gem/ruby/2.1.2/gems/puppet-3.6.2/lib/puppet/type.rb:1654:in `find_all'
    /home/igalic/.gem/ruby/2.1.2/gems/puppet-3.6.2/lib/puppet/type.rb:1654:in `defaultprovider'
    /home/igalic/.gem/ruby/2.1.2/gems/puppet-3.6.2/lib/puppet/type.rb:1159:in `providers_by_source'
    /home/igalic/.gem/ruby/2.1.2/gems/puppet-3.6.2/lib/puppet/type.rb:1128:in `instances'
    /home/igalic/.gem/ruby/2.1.2/gems/puppet-3.6.2/lib/puppet/indirector/resource/ral.rb:25:in `search'
    /home/igalic/.gem/ruby/2.1.2/gems/puppet-3.6.2/lib/puppet/indirector/indirection.rb:267:in `search'
    /home/igalic/.gem/ruby/2.1.2/gems/puppet-3.6.2/lib/puppet/application/resource.rb:226:in `find_or_save_resources'
    /home/igalic/.gem/ruby/2.1.2/gems/puppet-3.6.2/lib/puppet/application/resource.rb:143:in `main'
    /home/igalic/.gem/ruby/2.1.2/gems/puppet-3.6.2/lib/puppet/application.rb:379:in `run_command'
    /home/igalic/.gem/ruby/2.1.2/gems/puppet-3.6.2/lib/puppet/application.rb:371:in `block (2 levels) in run'
    /home/igalic/.gem/ruby/2.1.2/gems/puppet-3.6.2/lib/puppet/application.rb:477:in `plugin_hook'
    /home/igalic/.gem/ruby/2.1.2/gems/puppet-3.6.2/lib/puppet/application.rb:371:in `block in run'
    /home/igalic/.gem/ruby/2.1.2/gems/puppet-3.6.2/lib/puppet/util.rb:479:in `exit_on_fail'
    /home/igalic/.gem/ruby/2.1.2/gems/puppet-3.6.2/lib/puppet/application.rb:371:in `run'
    /home/igalic/.gem/ruby/2.1.2/gems/puppet-3.6.2/lib/puppet/util/command_line.rb:137:in `run'
    /home/igalic/.gem/ruby/2.1.2/gems/puppet-3.6.2/lib/puppet/util/command_line.rb:91:in `execute'
    /home/igalic/.gem/ruby/2.1.2/gems/puppet-3.6.2/bin/puppet:8:in `<top (required)>'
    /home/igalic/.gem/ruby/2.1.2/bin/puppet:23:in `load'
    /home/igalic/.gem/ruby/2.1.2/bin/puppet:23:in `<main>'